remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

title: Sugirdha
logo: /assets/img/profile.jpg
description: App Developer and Lifelong Learning Enthusiast

linkedin_url: "https://www.linkedin.com/in/Sugirdha/"
about: "/about"
tags_page: "/postbytags"

excerpt_separator: <!--more-->
