remote_theme: Sugirdha/beautiful-jekyll
plugins:
  - jekyll-remote-theme

title: Sugirdha's Blog
author: Sugirdha
logo: /assets/img/profile.jpg
description: App Developer and Lifelong Learning Enthusiast
favicon_img: "/assets/img/favicon.jpg"

excerpt_separator: <!--more-->

# linkedin_url: "https://www.linkedin.com/in/Sugirdha/"
# github_url: "https://github.com/Sugirdha"
# about: "/about"

#################################################################################
# --------------------------- Theme related changes --------------------------- #
# --------------------- Theme: Sugirdha/beautiful-jekyll ---------------------- #
#################################################################################

navbar-links:
  Home: "/"
  About: "about"
  LinkedIn: "https://www.linkedin.com/in/Sugirdha/"
  GitHub: "https://github.com/Sugirdha"
  # Resources:
  #   - Tags: "postbytags"

avatar: "/assets/img/profile.jpg"
round-avatar: true

social-network-links:
  github: Sugirdha
  linkedin: sugirdha

share-links-active:
  github: true
  linkedin: true

url-pretty: "Sugirdha's Blog"

# Add the website title to the title of every page
title-on-all-pages: true

# Excerpt word length - Truncate the excerpt of each post on the feed page to the specified number of words
excerpt_length: 50

# Whether or not to show an excerpt for every blog post in the feed page
feed_show_excerpt: true

# Whether or not to show a list of tags below each post preview in the feed page
feed_show_tags: true

# Add a search button to the navbar
post_search: true

# Add a button in the footer to edit the current page. Only works if your website is hosted on GitHub
edit_page_button: true

# Allow sub-menu items (second-level navigation menu items) to be longer than the top-level menu
# If this setting is off, then long sub-menu words might get cut off
# See https://github.com/daattali/beautiful-jekyll/issues/765 to understand the issue this setting can solve
navbar-var-length: false
# The keywords to associate with your website, for SEO purposes
# keywords: "my,list,of,keywords"

#navbar-img: "/assets/img/bgimage.png"
#footer-img: "/assets/img/bgimage.png"
#page-img: "/assets/img/bgimage.png"

site-css:
  - "/assets/css/custom.css"
#site-js:
#  - "/assets/js/custom-script.js"
#################################################################################
#################################################################################

#################################################################################
# --- You don't need to touch anything below here (but you can if you want) --- #
#################################################################################

# Output options (more information on Jekyll's site)
timezone: "Asia/Singapore"
markdown: kramdown
highlighter: rouge
# permalink: /:year-:month-:day-:title/
# paginate: 5

kramdown:
  input: GFM

# Default YAML values (more information on Jekyll's site)
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
  - scope:
      path: "" # any file that's not a post will be a "page" layout by default
    values:
      layout: "page"

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/
# plugins:
# - jekyll-paginate
# - jekyll-sitemap
